#!/usr/bin/env python

import os
import sys

#from os.path import join
#from seisflows.tools.tools import loadjson, loadobj
#from seisflows.config import load

def export(myenv):
    # exports comma delimited list of environment variables
    # e.g. VARNAME1=value1,VARNAME2=value2
    for item in myenv.split(','):
        os.environ.update([item.split('=')])


if __name__ == '__main__':
    """ Runs task within currently executing workflow
    """
    nargs = len(sys.argv[1:])

    # parse command line arguments
    mypath = sys.argv[1]
    myclass = sys.argv[2]
    myfunc = sys.argv[3]

    #if nargs == 4: 
    #    myenv = sys.argv[4].strip(',')
    #    export(myenv)

    #from os.path import join
    #from seisflows.tools.tools import loadjson, loadobj
    #from seisflows.config import load


    print 'Hello from test run  on node' + os.getenv('PBS_VNODENUM')
